# Generated by Django 2.0.6 on 2018-06-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FipeAPI', '0002_auto_20180628_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelareferencia',
            name='mes',
            field=models.CharField(max_length=32),
        ),
    ]
