# Generated by Django 2.0.6 on 2018-06-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FipeAPI', '0003_auto_20180628_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=32)),
            ],
        ),
    ]
