# Generated by Django 2.0.6 on 2018-06-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FipeAPI', '0004_tipoveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoveiculo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
