# Generated by Django 2.0.6 on 2018-06-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FipeAPI', '0006_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=128)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FipeAPI.Marca')),
            ],
        ),
    ]
