# Generated by Django 2.0.6 on 2018-06-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FipeAPI', '0007_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='tipo_veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FipeAPI.TipoVeiculo'),
            preserve_default=False,
        ),
    ]
