# Generated by Django 2.0.6 on 2018-07-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FipeAPI', '0009_auto_20180706_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='valor',
            name='mes_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FipeAPI.TabelaReferencia'),
        ),
        migrations.AlterField(
            model_name='valor',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
